name: Black

on: [push, pull_request]

jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: psf/black@stable
        with:
          options: "--color --verbose -t py38"
